### ISSUE TITLE
Let's start submitting PRs for changing code?

### ISSUE THREAD

**Issue by navidcy** [dhruvbhagtani2105/toy-model#10]
@dhruvbhagtani2105, I saw you pushed the Euler module.
I have some remarks on that. I'll raise an issue.

But let's start submitting PRs for modifying the code. That way we'll all have the chance to comment/review code before it's merge in the repository. It's anyway a good practice. ;)

**Comment by dhruvbhagtani** [comment]
Sure @navidcy. Happy to hear your thoughts.

**Comment by navidcy** [comment]
> Sure @navidcy. Happy to hear your thoughts.

I'm afraid I'm being repetitive here :(, but the gist of my comments is that the module is neither commented, nor docstring, nor tested. Perhaps we should revisit it after we discuss the [assignment](https://github.com/ANU-RSES-Education/EMSC-4033-assignment) on Fri?

**Comment by dhruvbhagtani** [comment]
Hi Navid - sorry for replying so late. I just finished commenting the [1D_diffusion.ipynb](https://github.com/dhruvbhagtani2105/toy-model/blob/master/1D_Diffusion.ipynb), [Periodic_boundary_conditions.ipynb](https://github.com/dhruvbhagtani2105/toy-model/blob/master/Periodic_boundary_conditions.ipynb) and the [Euler module](https://github.com/dhruvbhagtani2105/toy-model/tree/master/Euler) (this one partially). Each of them have been commented to some extent, and I've added docstrings to each function for easier readability.

**Comment by navidcy** [comment]
I'll go through it today tomorrow.

What happened with https://github.com/dhruvbhagtani2105/toy-model/issues/10? :)

**Comment by dhruvbhagtani** [comment]
Ah, I forgot. I've created a new branch - `Dhruv_codes`.

**Comment by navidcy** [comment]
So when you feel you have something ready to merge to main submit a PR? Or should I have a look at the branch?

**Comment by navidcy** [comment]
I'll close this issue since we are bypassing it. :)
